OnlineShopSystem/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopSystem.DB;
using OnlineShopSystem.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace OnlineShopSystem.Controllers
{
    public class AdministrationController : Controller
    {
        public IActionResult Index()
        {
            AuthController.CheckUserLoggedIn(this, true);
            return View();
        }

        public IActionResult EditShopSettings()
        {
            AuthController.CheckUserLoggedIn(this, true);
            return View();
        }

        public IActionResult EditCategories()
        {
            AuthController.CheckUserLoggedIn(this, true);
            List<CategoryViewModel> categories = new List<CategoryViewModel>();
            using (ApplicationContext db = new ApplicationContext())
            {
                var temp = db.Categories.ToList();
                foreach(var cat in temp)
                {
                    categories.Add(new CategoryViewModel(cat));
                }
            }
            ViewBag.Categories = categories;
            return View();
        }

        public IActionResult EditProducts(int? id)
        {
            AuthController.CheckUserLoggedIn(this, true);
            if (id == null)
            {
                ViewBag.Mode = "products";
                List<ProductViewModel> products = new List<ProductViewModel>();
                using (ApplicationContext db = new ApplicationContext())
                {
                    var temp = db.Products.ToList();
                    foreach(var prod in temp)
                    {
                        products.Add(new ProductViewModel(prod));
                    }
                }

                ViewBag.Products = products;
            }
            else if (id == 0)
            {
                ViewBag.Mode = "product";
                ProductViewModel product = new ProductViewModel();
                List<CategoryViewModel> categories = new List<CategoryViewModel>();
                using (ApplicationContext db = new ApplicationContext())
                {
                    var cats = db.Categories.ToList();
                    foreach (var cat in cats)
                    {
                        categories.Add(new CategoryViewModel(cat));
                    }
                }
                ViewBag.Product = product;
                ViewBag.Categories = categories;
            }
            else
            {
                ViewBag.Mode = "product";
                ProductViewModel product = null;
                List<CategoryViewModel> categories = new List<CategoryViewModel>();
                using (ApplicationContext db = new ApplicationContext())
                {
                    var temp = db.Products.Where(a => a.ID == id).ToList();
                    if (temp.Count != 0)
                    {
                        product = new ProductViewModel(temp[0]);
                    }
                    var cats = db.Categories.ToList();
                    foreach(var cat in cats)
                    {
                        categories.Add(new CategoryViewModel(cat));
                    }
                }
                ViewBag.Product = product;
                ViewBag.Categories = categories;
            }
            return View();
        }

        [HttpPost]
        public string EditShopSettingsR([FromBody] ShopSettingsDeserialization settings)
        {
            string json = JsonSerializer.Serialize(settings);
            System.IO.File.WriteAllText($"ShopSettingsBackup/ShopSettings_{DateTime.Now.ToString().Replace(":",".")}.json", System.IO.File.ReadAllText("ShopSettings.json"));
            System.IO.File.WriteAllText("ShopSettings.json", json);

            ShopSettings.Name = settings.Name;
            ShopSettings.Description = settings.Description;
            ShopSettings.PhoneNumber = settings.PhoneNumber;
            ShopSettings.Address = settings.Address;
            ShopSettings.Vk = settings.Vk;
            ShopSettings.Instagram = settings.Instagram;

            return JsonResponse.Success();
        }

        [HttpPost]
        public string EditCategoriesR([FromBody] List<CategoryViewModel> categories)
        {
            int errorsCount = 0;
            int changesCount = 0;
            int createdCount = 0;
            int removedCount = 0;
            using (ApplicationContext db = new ApplicationContext())
            {
                foreach (var category in categories)
                {
                    if (category.ID == 0)
                    {
                        db.Categories.Add(new Category() { Name = category.Name, Description = category.Description });
                        createdCount++;
                    }
                    else
                    {
                        var temp = db.Categories.Where(a => a.ID == category.ID).ToList();
                        if (temp.Count == 0)
                        {
                            errorsCount++;
                            continue;
                        }
                        if (category.Name == "" && category.Description == "")
                        {
                            db.Categories.Remove(temp[0]);
                            removedCount++;
                        }
                        else
                        {
                            if (temp[0].Name != category.Name)
                            {
                                temp[0].Name = category.Name;
                                changesCount++;
                            }
                            if (temp[0].Description != category.Description)
                            {
                                temp[0].Description = category.Description;
                                changesCount++;
                            }
                        }
                        
                    }
                }
                db.SaveChanges();
            }
            return JsonResponse.Success($"Errors:{errorsCount}; Fields changed:{changesCount}; Categories created:{createdCount}; Categories removed:{removedCount}");
        }

        [HttpPost]
        public string EditProductsR([FromBody] ProductViewModel product)
        {
            using (ApplicationContext db = new ApplicationContext())
            {
                if (product.ID == 0)
                {
                    db.Products.Add(new Product(product));
                }
                else
                {
                    var temp = db.Products.Where(a => a.ID == product.ID).ToList();
                    if (temp.Count == 0)
                    {
                        return JsonResponse.Error("No such product!");
                    }
                    else
                    {
                        //List<int> indexes = new List<int>();
                        //for (int i = 0; i < product.Images.Count; i++)
                        //{
                        //    if (product.Images[i] == "")
                        //    {
                        //        indexes.Add(i);
                        //    }
                        //}
                        //indexes.Reverse();
                        //foreach(var index in indexes)
                        //{
                        //    product.Images.RemoveAt(index);
                        //}
                        Product obj = new Product(product);
                        temp[0].Name = obj.Name;
                        temp[0].Description = obj.Description;
                        temp[0].Cost = obj.Cost;
                        temp[0].GoodsRemain = obj.GoodsRemain;
                        temp[0].Images = obj.Images;
                        temp[0].Category = obj.Category;
                    }
                }
                db.SaveChanges();
            }
            return JsonResponse.Success();
        }

        [HttpPost]
        public string DeleteProductR([FromBody] int id)
        {
            
            using (ApplicationContext db = new ApplicationContext())
            {
                var temp = db.Products.Where(a => a.ID == id).ToList();
                if (temp.Count != 0)
                {
                    db.Products.Remove(temp[0]);
                    db.SaveChanges();
                    return JsonResponse.Success();
                }
                return JsonResponse.Error("no such product!");
            }
        }


        public class UploadedFile
        {
            public string Name { get; set; }
            public string Content { get; set; }
        }

        [HttpPost]
        public string UploadImage([FromBody] UploadedFile file)
        {
            string filename = AuthController.CreateMD5(file.Name + DateTime.Now.ToString())+"." + file.Name.Split(".")[file.Name.Split(".").Length - 1];
            //System.IO.File.WriteAllText($"wwwroot/Data/Uploads/Images/{filename}", file.Content);
            var bytes = Convert.FromBase64String(file.Content.Split(",")[1]);
            System.IO.File.WriteAllBytes($"wwwroot/Data/Uploads/Images/{filename}", bytes);


            //using (var stream = new FileStream($"wwwroot/Data/Uploads/Images/{filename}", FileMode.Create))
            //{
            //    stream.Write(bytes, 0, bytes.Length);
            //    stream.Flush();
            //}

            return JsonResponse.Success(filename);
        }

        //[HttpPost]
        //public string UploadSiteIco([FromBody] UploadedFile file)
        //{
        //    string filename = "site_ico" + "." + file.Name.Split(".")[file.Name.Split(".").Length - 1];
        //    //System.IO.File.WriteAllText($"wwwroot/Data/Uploads/Images/{filename}", file.Content);
        //    var bytes = Convert.FromBase64String(file.Content.Split(",")[1]);

OnlineShopSystem/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopSystem.DB;
using OnlineShopSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShopSystem.Controllers
{
    public class ProductsController : Controller
    {

        public IActionResult Index()
        {
            //AuthController.CheckUserLoggedIn(this);
            List<CategoryViewModel> categories = new List<CategoryViewModel>();
            using (ApplicationContext db = new ApplicationContext())
            {
                var cats = db.Categories.ToList();
                foreach(var cat in cats)
                {
                    categories.Add(new CategoryViewModel(cat));
                }
            }
            ViewBag.Categories = categories;
            return View();
        }

        public IActionResult Category(int id)
        {
            CategoryViewModel category = null;
            List<ProductViewModel> products = new List<ProductViewModel>();
            using (ApplicationContext db = new ApplicationContext())
            {
                var temp = db.Categories.Where(a => a.ID == id).ToList();
                if (temp.Count == 0)
                {
                    
                }
                else
                {
                    category = new CategoryViewModel(temp[0]);
                    var prods = db.Products.Where(a => a.Category == temp[0].Name).ToList();
                    foreach(var prod in prods)
                    {
                        products.Add(new ProductViewModel(prod));
                    }
                }
            }
            ViewBag.Category = category;
            ViewBag.Products = products;
            return View();
        }

        public IActionResult Product(int id)
        {
            ProductViewModel product = null;
            using (ApplicationContext db = new ApplicationContext())
            {
                var temp = db.Products.Where(a => a.ID == id).ToList();
                if (temp.Count == 0)
                {

                }
                else
                {
                    product = new ProductViewModel(temp[0]);
                }
            }
            ViewBag.Product = product;
            return View();
        }
    }
}

OnlineShopSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] @ShopSettings.Name</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<img src="/Data/site_ico.png" alt="icon" />*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ShopSettings.Name</a>
                @*@if (OnlineShopSystem.Controllers.AuthController.GetCurrentUserRole((ControllerBase)ViewContext.RouteData.Values["controller"]) == "admin")
        {
            <a class="navbar-brand" asp-area="" asp-controller="Administration" asp-action="Index">Administration panel</a>
        }*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Catalog</a>
                </li>
            </ul>
        </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - @ShopSettings.Name
            @if (ShopSettings.PhoneNumber != "")
            {
                <a>@ShopSettings.PhoneNumber</a>
            }
            @if (ShopSettings.Address != "")
            {
                <a>@ShopSettings.Address</a>
            }
            @if (ShopSettings.Vk != "")
            {
                <a href="https://@ShopSettings.Vk">VK</a>
            }
            @if (ShopSettings.Instagram != "")
            {
                <a href="https://@ShopSettings.Instagram">Instagram</a>
            }
        </div>
        <style>
            header nav .container {
                text-align: center;
            }
            footer .container a {
                border-left: 1px solid gray;
                border-left: 1px solid gray;
                padding: 5px;
            }
        </style>
    </footer>
    <script>
        const cont = document.querySelector("header nav .navbar-collapse ul");

        if (document.cookie.includes("IsAdmin")) {
            cont.innerHTML += `<li class="nav-item">
                    <a class="nav-link text-dark" href="/Administration/Index">Administration panel</a>
                </li>`
        }
        if (document.cookie.includes("Session")) {
            cont.innerHTML += `<li class="nav-item">
                    <a class="nav-link text-dark" href="/Auth/Logout">Logout</a>
                </li>`
        }
        if (document.cookie.includes("Session")) {
            cont.innerHTML += `<li class="nav-item">
                    <a class="nav-link text-dark" href="/Basket/Index">Basket</a>
                </li>`
        }
        if (!document.cookie.includes("Session")) {
            cont.innerHTML += `<li class="nav-item">
                    <a class="nav-link text-dark" href="/Auth/Login">Login</a>
                </li>`
            cont.innerHTML += `<li class="nav-item">
                    <a class="nav-link text-dark" href="/Auth/Register">Register</a>
                </li>`
        }
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>